def get_label(index):
    LABELS = [
        'ং',
        'ঃ',
        'অ',
        'আ',
        'ই',
        'উ',
        'এ',
        'ও',
        'ক',
        'খ',
        'গ',
        'ঘ',
        'চ',
        'ছ',
        'জ',
        'ঝ',
        'ট',
        'ঠ',
        'ড',
        'ড়',
        'ঢ',
        'ত',
        'থ',
        'দ',
        'ধ',
        'ন',
        'প',
        'ফ',
        'ব',
        'ভ',
        'ম',
        'য়',
        'র',
        'ল',
        'স',
        'হ',
        '০',
        '১',
        '২',
        '৩',
        '৪',
        '৫',
        '৬',
        '৭',
        '৮',
        '৯'
    ]

    LABELS_MAP = {index: LABELS[index] for index in range(len(LABELS))}

    return LABELS_MAP[index]
